name: Update & Downport

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Run Commands
      run: |      
        git config user.email "downport@abapgit.org"
        git config user.name "Mr. Downport"
        git clone https://github.com/hdegroot/zwordle /tmp/new
        rm -rf src
        cp -rf /tmp/new/src src
        git add -A
        git commit -m "update base"
        git push        
        npm install @abaplint/cli
        npx abaplint --fix
        git status
        git add -A
        git commit -m "downport"
        git push
